const String USER_ID_SP = 'USER_ID_SP';
const String IS_DARK_SP = 'IS_DARK_SP';
const String PLAY_SONG_SHEET_ID = 'PLAY_SONG_SHEET_ID';
const String LAST_PLAY_INFO = 'LAST_PLAY_INFO';
const String USER_AVATAR = 'USER_AVATAR';
const String IS_IGNORE_AUDIO_FOCUS = 'IS_IGNORE_AUDIO_FOCUS';
const String IS_FIRST_OPEN = 'IS_FIRST_OPEN';
