name: Check & Test Rust Code

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-11
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - if: runner.os != 'Windows'
        uses: rui314/setup-mold@v1
      - if: runner.os != 'Windows'
        uses: taiki-e/install-action@nextest
      - if: runner.os != 'Windows'
        run: cargo nextest run && cargo test --doc
      - if: runner.os == 'Windows'
        run: cargo test

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/rustfmt@v1

  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo clippy
