name: Build Flutter APK

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main  # 或者你要构建的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # 版本可改成项目支持的版本

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: bujuan-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
